/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.VistasCliente;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import modelos.Aplicacion;
import utiles.ModeloTabla;
import utiles.Enum;
import utiles.Enum.DiaEnum;
import utiles.Enum.ClaseEnum;

/**
 *
 * @author docto
 */
public class InterfazBuscarClase extends javax.swing.JFrame {

    /**
     * Creates new form InterfazBuscarEquipo
     */
    public InterfazBuscarClase() {
        initComponents();
        inicializarDesplegables();
    }
    
    private void inicializarDesplegables(){
        jComboBoxDeporte.setSelectedIndex(0);
    }
    
    public void inicializarDesplegableNivel(JComboBox desplegableNivel, Enum.ClaseEnum tipoClase) {
        ArrayList<String> niveles = new ArrayList<>();
        if(tipoClase == Enum.ClaseEnum.FUTBOL){
            Enum.NivelFutbolEnum[] arrayNivelFutbol = Enum.NivelFutbolEnum.values();
            for (Enum.NivelFutbolEnum nivelFutbol : arrayNivelFutbol){
                niveles.add(String.valueOf(nivelFutbol));
            }
        } else{
            Enum.NivelPadelNatacionEnum[] arrayNivelPadelNatacion = Enum.NivelPadelNatacionEnum.values();
            for (Enum.NivelPadelNatacionEnum nivelNatPad : arrayNivelPadelNatacion){
                niveles.add(String.valueOf(nivelNatPad));
            }
        }
        
        String[] array = new String[niveles.size()];
        for (int i=0; i<niveles.size(); i++){
            array[i] = niveles.get(i);
        }
        
        jComboBoxNivel.setModel(new DefaultComboBoxModel<>(array));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxDeporte = new javax.swing.JComboBox<>();
        jComboBoxNivel = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        infoClase = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Buscar Clase");

        jComboBoxDeporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUTBOL", "PADEL", "NATACION" }));
        jComboBoxDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDeporteActionPerformed(evt);
            }
        });

        jComboBoxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNivelActionPerformed(evt);
            }
        });

        jLabel2.setText("Deporte");

        jLabel4.setText("Nivel");

        infoClase.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoClase.setText("Info clase");

        jButton1.setText("Apuntarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(infoClase, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(82, 82, 82)
                .addComponent(infoClase, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDeporteActionPerformed
        inicializarDesplegableNivel(jComboBoxNivel, Enum.ClaseEnum.valueOf(String.valueOf(jComboBoxDeporte.getSelectedItem())));
        jComboBoxNivel.setSelectedIndex(0);
    }//GEN-LAST:event_jComboBoxDeporteActionPerformed

    private void jComboBoxNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNivelActionPerformed
        infoClase.setText(
                app.getClase(String.valueOf(jComboBoxDeporte.getSelectedItem()), String.valueOf(jComboBoxNivel.getSelectedItem()))
                .getInformacion()
        );
    }//GEN-LAST:event_jComboBoxNivelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //app.apuntarSocioClase(app.getUsuarioLogueado(), app.getClase(String.valueOf(jComboBoxDeporte.getSelectedItem()), String.valueOf(jComboBoxNivel.getSelectedItem())));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoClase;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxDeporte;
    private javax.swing.JComboBox<String> jComboBoxNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
    private Aplicacion app = Aplicacion.getInstancia();
}
