/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.VistasMonitor;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelos.Aplicacion;
import modelos.Usuarios.Usuario;
import modelos.FabricaRutina.*;
import modelos.Usuarios.Socio;
/**
 *
 * @author docto
 */
public class VistaRutina extends javax.swing.JFrame {

    private JFrame anterior;
    /**
     * Creates new form VistaRutina
     */
    public VistaRutina(JFrame anterior) {
        initComponents();
        this.anterior = anterior;
        anterior.setVisible(false);
        inicializarDesplegableNombres(jComboBoxNombre, app.getSocios());
    }
    
    public void inicializarDesplegableNombres(JComboBox desplegableNombres,List<Socio> socios) {
        ArrayList<String> nombres = new ArrayList<>();
        
        if(socios.size() != 0){
            for (int i=0;i<socios.size();i++){
                nombres.add(socios.get(i).getCorreo());
            } 
    }

        String[] array = new String[nombres.size()];
        for (int i = 0; i < nombres.size(); i++) {
            array[i] = nombres.get(i);
        }

        jComboBoxNombre.setModel(new DefaultComboBoxModel<>(array));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxNombre = new javax.swing.JComboBox<>();
        jComboBoxTipoRutina = new javax.swing.JComboBox<>();
        jButtonCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rutina");

        jComboBoxNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNombreActionPerformed(evt);
            }
        });

        jComboBoxTipoRutina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Principiante", "Intermedio", "Avanzado" }));

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTipoRutina, 0, 181, Short.MAX_VALUE))
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButtonCrear)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jComboBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jComboBoxTipoRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButtonCrear)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNombreActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        Rutina rutina;
        switch (String.valueOf(jComboBoxTipoRutina.getSelectedItem())) {
            case "Principiante":
                rutina = fp.crearEjercicios();
                break;
            case "Intermedio":
                rutina = fi.crearEjercicios();
                break;
            default:
                rutina = fa.crearEjercicios();
                break;
        }
        app.getSocio((String)jComboBoxNombre.getSelectedItem()).setRutina(rutina);
        JOptionPane.showMessageDialog(this, "Se ha creado la rutina correctamente", "FITTRONES", JOptionPane.INFORMATION_MESSAGE);
        anterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        anterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<String> jComboBoxNombre;
    private javax.swing.JComboBox<String> jComboBoxTipoRutina;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
private Aplicacion app = Aplicacion.getInstancia();
private FactoriaAvanzado fa = new FactoriaAvanzado();
private FactoriaIntermedio fi = new FactoriaIntermedio();
private FactoriaPrincipiante fp = new FactoriaPrincipiante();

}
