/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces.VistasMonitor;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelos.Usuarios.Socio;
import modelos.Aplicacion;
import modelos.DietaBuilder.Dieta;
import modelos.DietaBuilder.DietaDefinicionBuilder;
import modelos.DietaBuilder.DietaVolumenBuilder;
import modelos.Usuarios.Usuario;
import modelos.Usuarios.Monitor;

/**
 *
 * @author docto
 */
public class VistaDieta extends javax.swing.JFrame {

    private JFrame anterior;
    /**
     * Creates new form VistaDieta
     */
    public VistaDieta(JFrame anterior) {
        initComponents();
        this.anterior = anterior;
        anterior.setVisible(false);
        inicializarDesplegableNombres(jComboNombres, app.getSocios());
    }
    
    public void inicializarDesplegableNombres(JComboBox desplegableNombres,List<Socio> socios) {
        ArrayList<String> nombres = new ArrayList<>();
        
        
        for (int i=0;i<socios.size();i++){
            nombres.add(socios.get(i).getCorreo());
        } 

        String[] array = new String[nombres.size()];
        for (int i = 0; i < nombres.size(); i++) {
            array[i] = nombres.get(i);
        }

        jComboNombres.setModel(new DefaultComboBoxModel<>(array));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboNombres = new javax.swing.JComboBox<>();
        jComboTipoDieta = new javax.swing.JComboBox<>();
        jButtonCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dieta");

        jComboNombres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNombresActionPerformed(evt);
            }
        });

        jComboTipoDieta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Definición", "Volumen" }));

        jButtonCrear.setText("Crear");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jComboTipoDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jComboNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jButtonCrear)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jComboNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jComboTipoDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButtonCrear)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNombresActionPerformed
        
    }//GEN-LAST:event_jComboNombresActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
       if (String.valueOf(jComboTipoDieta.getSelectedItem()).equals("Definición")){
           Monitor monitor = (Monitor)app.getUsuarioLogueado();
           monitor.setDietaBuilder(def);
           monitor.crearListaDietas();
           dieta = monitor.getListaDietas();
       }else{
           Monitor monitor = (Monitor)app.getUsuarioLogueado();
           monitor.setDietaBuilder(vo);
           monitor.crearListaDietas();
           dieta = monitor.getListaDietas();
       }
       app.getSocio((String)jComboNombres.getSelectedItem()).setDieta(dieta);
       JOptionPane.showMessageDialog(this, "Se ha creado la dieta correctamente", "FITTRONES", JOptionPane.INFORMATION_MESSAGE);
       anterior.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        anterior.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JComboBox<String> jComboNombres;
    private javax.swing.JComboBox<String> jComboTipoDieta;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
 private Aplicacion app = Aplicacion.getInstancia();
 private DietaDefinicionBuilder def = new DietaDefinicionBuilder();
 private DietaVolumenBuilder vo = new DietaVolumenBuilder();
 private Dieta dieta;
}
